Repository FppEpitech/MyTorch, pull requests merged in 2024-12, with the labels that each got.

#6 Add the CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#8 docs (issue template): Added issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom-issue.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#7 Add the README.md
  README.md
Labels: documentation

#17 fix(ci): Check executables workoflow
  .github/workflows/check.yml
Labels: bug

#18 fix(ci): remove make clean command of the check executables
  .github/workflows/check.yml
Labels: bug

#19 fix (ci): remove check executables workflow
  .github/workflows/check.yml
Labels: bug

#13 Feat/add the root makefile
  .gitignore
  Makefile
  src/analyser/main.py
  src/generator/main.py
Labels: enhancement

#16 FEAT: Parse command
  src/analyser/main.py
  src/commandParsing/commandParsing.py
  src/generator/main.py
Labels: enhancement

#23 Feat/create generator
  .gitignore
  src/generator/Generator.py
  src/generator/ParseConfig.py
  src/generator/PerceptronLite.py
  src/generator/main.py
Labels: enhancement

#25 FEAT: Create the multi perceptron
  src/analyser/multi_perceptron.py
  src/analyser/perceptron.py
Labels: enhancement

#31 FEAT: Linked prediction mode with MLP and data parsing
  src/analyzer/main.py
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
  src/datasetParsing/datasetParsing.py
  src/generator/Generator.py
Labels: enhancement

#35 FEAT: Handle display output
  src/analyzer/main.py
  src/analyzer/multi_perceptron.py
Labels: enhancement

#36 feat: enhance Generator and ParseConfig to support activation functio…
  src/generator/Generator.py
  src/generator/ParseConfig.py
  src/generator/PerceptronLite.py
  src/generator/main.py
Labels: enhancement

#39 feat(analyser): implement network initialization from loading file (.nn)
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
Labels: enhancement

#43 refactor: rename variables in Generator and remove some variable of t…
  src/generator/Generator.py
  src/generator/ParseConfig.py
Labels: enhancement

#46 FIX: Change type of inputs
  src/analyzer/main.py
  src/datasetParsing/datasetParsing.py
  src/generator/Generator.py
Labels: bug

#47 feat(analyser): Add parsing of activation functions
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
Labels: enhancement

#48 feat(analyser): Add save network functionality
  src/analyzer/main.py
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
  src/generator/PerceptronLite.py
Labels: enhancement

#49 FEAT: .nn for Automated tests
  .gitignore
  config_1.nn
Labels: enhancement

#50 FIX: Hotfix notrain
  config_file
  my_torch_network.nn
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
  src/generator/Generator.py
  train.sh
Labels: bug, enhancement

#51 FIX: Backward propagation in hidden layers
  mathieu/datasets/dataset1.txt
  mathieu/datasets/dataset2.txt
  mathieu/neurons/config_file_1.nn
  mathieu/neurons/config_file_2.nn
  src/analyzer/main.py
  src/analyzer/multi_perceptron.py
  src/analyzer/perceptron.py
Labels: bug
